#!/usr/bin/env node
// Runtime unit tests for siteasy live-mode path containment, design-system
// slug sanitisation, and the contrast parser's colour spaces.
// Pure Node standard library. Run: node tests/unit.mjs
import { resolveInRoot, looksGenerated } from "../skills/siteasy/scripts/live-core.mjs";
import { parseColor, ratioOf } from "../tools/audit/lib/contrast.mjs";
import { runChecks } from "../tools/audit/lib/checks.mjs";
import { resolve } from "node:path";

let failures = 0;
function ok(name, cond) {
  if (cond) console.log(`  ✅  ${name}`);
  else { console.error(`  ❌  ${name}`); failures++; }
}

console.log("\n── resolveInRoot: stays inside the project root ──");
const root = resolve("/proj");
ok("plain file resolves under root", resolveInRoot(root, "a.txt") === resolve(root, "a.txt"));
ok("nested file resolves under root", resolveInRoot(root, "sub/a.txt") === resolve(root, "sub/a.txt"));
ok("inner ../ that stays inside is allowed", resolveInRoot(root, "sub/../a.txt") === resolve(root, "a.txt"));

console.log("\n── resolveInRoot: rejects escapes ──");
ok("../ escape rejected", resolveInRoot(root, "../escape.txt") === null);
ok("deep ../ escape rejected", resolveInRoot(root, "a/../../escape.txt") === null);
ok("absolute path rejected", resolveInRoot(root, "/etc/passwd") === null);
ok("empty string rejected", resolveInRoot(root, "") === null);
ok("non-string rejected", resolveInRoot(root, null) === null);

console.log("\n── looksGenerated: detects generated-file markers ──");
ok("@generated detected", looksGenerated("// @generated by tool\nbody") === true);
ok("DO NOT EDIT detected", looksGenerated("/* DO NOT EDIT */\nbody") === true);
ok("plain content not flagged", looksGenerated("hello world") === false);

// ---------------------------------------------------------------------------
// contrast.mjs colour parsing.
//
// Anchored on values with known-exact answers (the sRGB primaries round-trip
// through every space, and oklch(62.8% 0.258 29.23) is CSS Color 4's own red
// sample) rather than on whatever this implementation happens to emit.
console.log("\n── parseColor: modern colour spaces ──");
const hex = (c) => {
  const p = parseColor(c);
  return p ? "#" + [p.r, p.g, p.b].map((n) => n.toString(16).padStart(2, "0")).join("") : null;
};

ok("oklch black", hex("oklch(0 0 0)") === "#000000");
ok("oklch white", hex("oklch(1 0 0)") === "#ffffff");
ok("oklch red (CSS Color 4 sample)", hex("oklch(62.8% 0.258 29.23)") === "#ff0000");
ok("oklch percent lightness", hex("oklch(100% 0 0)") === "#ffffff");
ok("oklab achromatic is not sRGB mid-grey", hex("oklab(0.5 0 0)") === "#636363");
ok("lab white", hex("lab(100% 0 0)") === "#ffffff");
ok("lab red (D50)", hex("lab(54.29% 80.8 69.89)") === "#ff0000");
ok("lab green (D50)", hex("lab(87.82% -79.27 80.99)") === "#00ff00");
ok("lab blue (D50)", hex("lab(29.57% 68.3 -112.03)") === "#0000ff");
ok("lch red", hex("lch(54.29% 106.84 40.86)") === "#ff0000");
ok("hsl space syntax", hex("hsl(210 40% 96%)") === "#f1f5f9");
ok("hsl legacy comma syntax", hex("hsl(0, 100%, 50%)") === "#ff0000");
ok("hsl hue wraps", hex("hsl(360 100% 50%)") === "#ff0000");

console.log("\n── parseColor: alpha, legacy syntax, and honest failure ──");
ok("oklch slash alpha", parseColor("oklch(0.7 0.1 200 / 50%)")?.a === 0.5);
ok("hsla slash alpha", parseColor("hsla(120 100% 25% / 0.5)")?.a === 0.5);
ok("hsla legacy 4th arg alpha", parseColor("hsla(120, 100%, 25%, 0.5)")?.a === 0.5);
ok("`none` channel treated as 0", hex("oklch(1 none none)") === "#ffffff");
ok("hex still parses", hex("#f9f8f6") === "#f9f8f6");
ok("rgb still parses", hex("rgb(20 20 24)") === "#141418");
// An unsupported space must stay null so the caller reports "unreadable",
// never a silently wrong ratio.
ok("unsupported color() returns null", parseColor("color(display-p3 1 0 0)") === null);
ok("garbage returns null", parseColor("not-a-colour") === null);

console.log("\n── ratioOf: WCAG anchors ──");
ok("white on black is 21:1", ratioOf("#fff", "#000")?.ratio === 21);
ok("oklch white on oklch black is 21:1", ratioOf("oklch(1 0 0)", "oklch(0 0 0)")?.ratio === 21);
ok("identical colours are 1:1", ratioOf("#808080", "#808080")?.ratio === 1);
// The regression this whole parser exists for: an all-OKLCH token set used to
// return null here, so L-CONTRAST-1 passed without measuring anything.
ok("an OKLCH token pair yields a real ratio", ratioOf("oklch(96% 0.004 265)", "oklch(17% 0.007 265)")?.ratio > 15);
ok("unreadable colour yields null, not a guess", ratioOf("color(display-p3 1 0 0)", "#000") === null);

// ---------------------------------------------------------------------------
// Contrast exemptions.
//
// These test the POLICY, not the plumbing. The exemption exists so an author can
// overrule us out loud; every test below is one way that could rot into a mute
// button, pinned so it cannot. If someone loosens the rule, one of these fails and
// says which promise was dropped.
console.log("\n── contrast exemptions: declared, priced, never silent ──");
const sample = (over) => ({ ratio: 2.0, threshold: 4.5, fontSizePx: 12, exempt: null, exemptReason: null, ...over });
const run = (samples, html = "<html><body><p>x</p></body></html>") =>
  runChecks({ rawHtml: html, computed: { contrastSamples: samples } });
const check = (r, id) => r.find((c) => c.id === id);

const plain = check(run([sample({})]), "contrast-ratio");
ok("an undeclared low sample still fails", plain.verdict === "FAIL" && plain.value.failures === 1);

const declared = check(run([sample({ exempt: "staging", exemptReason: "depicts a defect on purpose" })]), "contrast-ratio");
ok("a properly declared exemption leaves the verdict", declared.verdict === "PASS");
ok("...but is still counted and shown", declared.value.exempt === 1 && declared.value.failures === 0);
ok("...and the report refuses to call it conformant",
  /not WCAG exceptions/.test(declared.detail) && /non-conformant/.test(declared.detail));

// The mute-button paths. Each of these MUST keep the sample in the failure count.
const noReason = check(run([sample({ exempt: "staging" })]), "contrast-ratio");
ok("an exemption without a reason does not excuse anything", noReason.verdict === "FAIL" && noReason.value.failures === 1);
const badCode = check(run([sample({ exempt: "because-i-said-so", exemptReason: "trust me" })]), "contrast-ratio");
ok("an exemption with an invented code does not excuse anything", badCode.verdict === "FAIL" && badCode.value.failures === 1);

// A WCAG-sanctioned code is exempt WITHOUT the non-conformance warning: unlike
// "staging", 1.4.3 actually grants these, so claiming otherwise would be a lie too.
const logo = check(run([sample({ exempt: "logotype", exemptReason: "the mark is the brand" })]), "contrast-ratio");
ok("a real WCAG exception is not smeared with the warning",
  logo.verdict === "PASS" && logo.value.exempt === 1 && !/non-conformant/.test(logo.detail));

console.log("\n── contrast-exempt-undeclared: the exemption pays its own price ──");
const declHtml = (attrs) => `<html><body><b ${attrs}>FAIL</b></body></html>`;
ok("no exemptions on the page passes quietly",
  check(runChecks({ rawHtml: "<html><body><p>x</p></body></html>" }), "contrast-exempt-undeclared").verdict === "PASS");
ok("a bare data-contrast-exempt is itself a defect",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="staging"') }), "contrast-exempt-undeclared").verdict === "FAIL");
ok("an unknown code is itself a defect",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="whatever" data-contrast-exempt-reason="x"') }), "contrast-exempt-undeclared").verdict === "FAIL");
ok("an empty reason does not count as a reason",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="staging" data-contrast-exempt-reason="   "') }), "contrast-exempt-undeclared").verdict === "FAIL");
ok("code plus a real reason passes",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="staging" data-contrast-exempt-reason="depicts the audit overlay"') }), "contrast-exempt-undeclared").verdict === "PASS");
// Static by design: it must work on a page that never booted.
ok("it works render-free, straight off the markup",
  check(runChecks({ rawHtml: declHtml('data-contrast-exempt="staging"') }), "contrast-exempt-undeclared").method === "static");

console.log("\n" + "═".repeat(50));
if (failures > 0) {
  console.error(`❌  unit tests FAILED: ${failures} failure(s).`);
  process.exit(1);
}
console.log("✅  unit tests passed.");
process.exit(0);
