#!/usr/bin/env node
// Runtime unit tests for siteasy live-mode path containment, design-system
// slug sanitisation, and the contrast parser's colour spaces.
// Pure Node standard library. Run: node tests/unit.mjs
import { resolveInRoot, looksGenerated } from "../skills/siteasy/scripts/live-core.mjs";
import { parseColor, ratioOf } from "../tools/audit/lib/contrast.mjs";
import { resolve } from "node:path";

let failures = 0;
function ok(name, cond) {
  if (cond) console.log(`  ✅  ${name}`);
  else { console.error(`  ❌  ${name}`); failures++; }
}

console.log("\n── resolveInRoot: stays inside the project root ──");
const root = resolve("/proj");
ok("plain file resolves under root", resolveInRoot(root, "a.txt") === resolve(root, "a.txt"));
ok("nested file resolves under root", resolveInRoot(root, "sub/a.txt") === resolve(root, "sub/a.txt"));
ok("inner ../ that stays inside is allowed", resolveInRoot(root, "sub/../a.txt") === resolve(root, "a.txt"));

console.log("\n── resolveInRoot: rejects escapes ──");
ok("../ escape rejected", resolveInRoot(root, "../escape.txt") === null);
ok("deep ../ escape rejected", resolveInRoot(root, "a/../../escape.txt") === null);
ok("absolute path rejected", resolveInRoot(root, "/etc/passwd") === null);
ok("empty string rejected", resolveInRoot(root, "") === null);
ok("non-string rejected", resolveInRoot(root, null) === null);

console.log("\n── looksGenerated: detects generated-file markers ──");
ok("@generated detected", looksGenerated("// @generated by tool\nbody") === true);
ok("DO NOT EDIT detected", looksGenerated("/* DO NOT EDIT */\nbody") === true);
ok("plain content not flagged", looksGenerated("hello world") === false);

// ---------------------------------------------------------------------------
// contrast.mjs colour parsing.
//
// Anchored on values with known-exact answers (the sRGB primaries round-trip
// through every space, and oklch(62.8% 0.258 29.23) is CSS Color 4's own red
// sample) rather than on whatever this implementation happens to emit.
console.log("\n── parseColor: modern colour spaces ──");
const hex = (c) => {
  const p = parseColor(c);
  return p ? "#" + [p.r, p.g, p.b].map((n) => n.toString(16).padStart(2, "0")).join("") : null;
};

ok("oklch black", hex("oklch(0 0 0)") === "#000000");
ok("oklch white", hex("oklch(1 0 0)") === "#ffffff");
ok("oklch red (CSS Color 4 sample)", hex("oklch(62.8% 0.258 29.23)") === "#ff0000");
ok("oklch percent lightness", hex("oklch(100% 0 0)") === "#ffffff");
ok("oklab achromatic is not sRGB mid-grey", hex("oklab(0.5 0 0)") === "#636363");
ok("lab white", hex("lab(100% 0 0)") === "#ffffff");
ok("lab red (D50)", hex("lab(54.29% 80.8 69.89)") === "#ff0000");
ok("lab green (D50)", hex("lab(87.82% -79.27 80.99)") === "#00ff00");
ok("lab blue (D50)", hex("lab(29.57% 68.3 -112.03)") === "#0000ff");
ok("lch red", hex("lch(54.29% 106.84 40.86)") === "#ff0000");
ok("hsl space syntax", hex("hsl(210 40% 96%)") === "#f1f5f9");
ok("hsl legacy comma syntax", hex("hsl(0, 100%, 50%)") === "#ff0000");
ok("hsl hue wraps", hex("hsl(360 100% 50%)") === "#ff0000");

console.log("\n── parseColor: alpha, legacy syntax, and honest failure ──");
ok("oklch slash alpha", parseColor("oklch(0.7 0.1 200 / 50%)")?.a === 0.5);
ok("hsla slash alpha", parseColor("hsla(120 100% 25% / 0.5)")?.a === 0.5);
ok("hsla legacy 4th arg alpha", parseColor("hsla(120, 100%, 25%, 0.5)")?.a === 0.5);
ok("`none` channel treated as 0", hex("oklch(1 none none)") === "#ffffff");
ok("hex still parses", hex("#f9f8f6") === "#f9f8f6");
ok("rgb still parses", hex("rgb(20 20 24)") === "#141418");
// An unsupported space must stay null so the caller reports "unreadable",
// never a silently wrong ratio.
ok("unsupported color() returns null", parseColor("color(display-p3 1 0 0)") === null);
ok("garbage returns null", parseColor("not-a-colour") === null);

console.log("\n── ratioOf: WCAG anchors ──");
ok("white on black is 21:1", ratioOf("#fff", "#000")?.ratio === 21);
ok("oklch white on oklch black is 21:1", ratioOf("oklch(1 0 0)", "oklch(0 0 0)")?.ratio === 21);
ok("identical colours are 1:1", ratioOf("#808080", "#808080")?.ratio === 1);
// The regression this whole parser exists for: an all-OKLCH token set used to
// return null here, so L-CONTRAST-1 passed without measuring anything.
ok("an OKLCH token pair yields a real ratio", ratioOf("oklch(96% 0.004 265)", "oklch(17% 0.007 265)")?.ratio > 15);
ok("unreadable colour yields null, not a guess", ratioOf("color(display-p3 1 0 0)", "#000") === null);

console.log("\n" + "═".repeat(50));
if (failures > 0) {
  console.error(`❌  unit tests FAILED: ${failures} failure(s).`);
  process.exit(1);
}
console.log("✅  unit tests passed.");
process.exit(0);
